# Generated by Django 4.2.30 on 2026-08-07 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
        ('pos', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveStorage',
            fields=[
                ('archive_ID', models.AutoField(primary_key=True, serialize=False)),
                ('module_table', models.CharField(max_length=100)),
                ('record_ID', models.IntegerField()),
                ('archived_data', models.TextField()),
                ('archived_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductClassification',
            fields=[
                ('classification_ID', models.AutoField(primary_key=True, serialize=False)),
                ('classification', models.CharField(max_length=50)),
                ('recommended_action', models.TextField()),
                ('classified_time', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.product')),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptiveOutput',
            fields=[
                ('prescriptive_output_ID', models.AutoField(primary_key=True, serialize=False)),
                ('output_type', models.CharField(max_length=100)),
                ('recommendation', models.TextField()),
                ('justification', models.TextField()),
                ('recommended_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('recommended_date', models.DateField(blank=True, null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(max_length=50)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.branch')),
                ('constraint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.constraintparameter')),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.ingredient')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos.product')),
            ],
        ),
        migrations.CreateModel(
            name='KPIRecord',
            fields=[
                ('kpi_ID', models.AutoField(primary_key=True, serialize=False)),
                ('inventory_turnover', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gmroi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gross_margin', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('dead_stock_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stockout_count', models.IntegerField()),
                ('period_date', models.DateField()),
                ('computed_time', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.branch')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalVariable',
            fields=[
                ('variable_ID', models.AutoField(primary_key=True, serialize=False)),
                ('variable_type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('impact_level', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.branch')),
            ],
        ),
        migrations.CreateModel(
            name='ChatbotLog',
            fields=[
                ('chatbot_log_ID', models.AutoField(primary_key=True, serialize=False)),
                ('query_text', models.TextField()),
                ('response_text', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.branch')),
                ('prescriptive_output', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics.prescriptiveoutput')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
