# Generated by Django 4.2.30 on 2026-08-07 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
        ('accounts', '0001_initial'),
        ('inventory', '0001_initial'),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptiveoutput',
            name='is_overridden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prescriptiveoutput',
            name='override_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatbotlog',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_logs', to='accounts.branch'),
        ),
        migrations.AlterField(
            model_name='externalvariable',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_variables', to='accounts.branch'),
        ),
        migrations.AlterField(
            model_name='kpirecord',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_records', to='accounts.branch'),
        ),
        migrations.AlterField(
            model_name='kpirecord',
            name='stockout_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='prescriptiveoutput',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptive_outputs', to='accounts.branch'),
        ),
        migrations.AlterField(
            model_name='prescriptiveoutput',
            name='constraint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.constraintparameter'),
        ),
        migrations.AlterField(
            model_name='prescriptiveoutput',
            name='ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.ingredient'),
        ),
        migrations.AlterField(
            model_name='prescriptiveoutput',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.product'),
        ),
        migrations.AlterField(
            model_name='prescriptiveoutput',
            name='status',
            field=models.CharField(default='Pending Review', max_length=50),
        ),
        migrations.AlterField(
            model_name='productclassification',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='pos.product'),
        ),
    ]
