# Generated by Django 4.2.30 on 2026-09-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_otprecord_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprecord',
            name='otp_code',
            field=models.CharField(max_length=6),
        ),
    ]
