# Generated by Django 4.2.30 on 2026-08-07 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('ingredient_ID', models.AutoField(primary_key=True, serialize=False)),
                ('ingredient_name', models.CharField(max_length=255)),
                ('measurement_unit', models.CharField(max_length=50)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientStock',
            fields=[
                ('ingredient_inventory_ID', models.AutoField(primary_key=True, serialize=False)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=100, null=True)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity_available', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reorder_threshold', models.DecimalField(decimal_places=2, max_digits=10)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.branch')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('product_inventory_ID', models.AutoField(primary_key=True, serialize=False)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=100, null=True)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity_available', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reorder_threshold', models.DecimalField(decimal_places=2, max_digits=10)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.product')),
            ],
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('adjustments_ID', models.AutoField(primary_key=True, serialize=False)),
                ('adjustment_type', models.CharField(max_length=50)),
                ('quantity_change', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField()),
                ('latest_update', models.DateTimeField(auto_now=True)),
                ('ingredient_inventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.ingredientstock')),
                ('product_inventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.productstock')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RestockRequest',
            fields=[
                ('restock_ID', models.AutoField(primary_key=True, serialize=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('requested_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=50)),
                ('request_finished', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approving_user', to=settings.AUTH_USER_MODEL)),
                ('destination_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_branch', to='accounts.branch')),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.ingredient')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos.product')),
                ('source_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_branch', to='accounts.branch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requesting_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConstraintParameter',
            fields=[
                ('constraint_ID', models.AutoField(primary_key=True, serialize=False)),
                ('lead_time_days', models.IntegerField()),
                ('min_order_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_order_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('production_limit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacity_limit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('latest_update', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.branch')),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.ingredient')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos.product')),
            ],
        ),
        migrations.CreateModel(
            name='BillOfMaterial',
            fields=[
                ('bom_ID', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_required', models.DecimalField(decimal_places=2, max_digits=10)),
                ('measurement_unit', models.CharField(max_length=50)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.ingredient')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.product')),
            ],
        ),
    ]
