# Generated by Django 4.2.30 on 2026-08-07 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pos', '0001_initial'),
        ('accounts', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockadjustment',
            old_name='ingredient_inventory',
            new_name='ingredients_inventory',
        ),
        migrations.AlterField(
            model_name='billofmaterial',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.ingredient'),
        ),
        migrations.AlterField(
            model_name='billofmaterial',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_ingredients', to='pos.product'),
        ),
        migrations.AlterField(
            model_name='constraintparameter',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constraints', to='accounts.branch'),
        ),
        migrations.AlterField(
            model_name='ingredientstock',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_stocks', to='accounts.branch'),
        ),
        migrations.AlterField(
            model_name='ingredientstock',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='inventory.ingredient'),
        ),
        migrations.AlterField(
            model_name='productstock',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_stocks', to='accounts.branch'),
        ),
        migrations.AlterField(
            model_name='productstock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='pos.product'),
        ),
        migrations.AlterField(
            model_name='restockrequest',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_restocks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='restockrequest',
            name='destination_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_restocks', to='accounts.branch'),
        ),
        migrations.AlterField(
            model_name='restockrequest',
            name='source_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_restocks', to='accounts.branch'),
        ),
        migrations.AlterField(
            model_name='restockrequest',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_restocks', to=settings.AUTH_USER_MODEL),
        ),
    ]
