# Generated by Django 4.2.30 on 2026-09-04 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_ingredient_inventory_stockadjustment_ingredients_inventory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstock',
            name='low_stock_threshold',
            field=models.IntegerField(default=5),
        ),
    ]
