# Generated by Django 4.2.30 on 2026-09-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_productstock_quantity_available_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productstock',
            name='low_stock_threshold',
        ),
        migrations.AlterField(
            model_name='productstock',
            name='reorder_threshold',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=10),
        ),
    ]
