# Generated by Django 4.2.30 on 2026-09-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_productstock_low_stock_threshold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientstock',
            name='quantity_available',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ingredientstock',
            name='reorder_threshold',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ingredientstock',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
