# Generated by Django 4.2.30 on 2026-09-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_ingredientstock_quantity_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constraintparameter',
            name='capacity_limit',
            field=models.DecimalField(decimal_places=2, default=9999.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='constraintparameter',
            name='lead_time_days',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='constraintparameter',
            name='max_order_quantity',
            field=models.DecimalField(decimal_places=2, default=9999.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='constraintparameter',
            name='min_order_quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='constraintparameter',
            name='production_limit',
            field=models.DecimalField(decimal_places=2, default=9999.0, max_digits=10),
        ),
    ]
